# Generated by Django 4.2.4 on 2023-08-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="read_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="write_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
