# Generated by Django 4.2.4 on 2023-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_document_read_code_document_write_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
