# Generated by Django 4.2.4 on 2023-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_user_avatar_user_description_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
