# Generated by Django 4.2.4 on 2023-08-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('image', models.ImageField(upload_to='interfaceDesign/page_images/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('button', 'Button'), ('textbox', 'Textbox')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='InterfaceDesign.page')),
            ],
        ),
    ]
