# Generated by Django 4.2.4 on 2023-08-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_document_read_code_document_write_code"),
        ("Chatroom", "0003_editmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="editmessage",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.document",
            ),
        ),
    ]
