# Generated by Django 4.2.4 on 2023-08-30 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_document_read_code_document_write_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chatroom', '0004_editmessage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_defalut_chatgroup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_disbanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.team'),
        ),
        migrations.CreateModel(
            name='ChatGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatroom.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chat_group')},
            },
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_groups', through='Chatroom.ChatGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
